ci: commit before retry tox

diff --git a/.github/workflows/continuous_integration.yml b/.github/workflows/continuous_integration.yml
--- a/.github/workflows/continuous_integration.yml
+++ b/.github/workflows/continuous_integration.yml
@@ -176,8 +176,21 @@ jobs:
           until [ $attempt -ge $max_attempts ]
           do
             tox -e release -- ${{ env.version_type }} && break
+            exit_code=$?
+
+            if [ $exit_code -eq 0 ]; then
+              break  # Success
+            elif [ $exit_code -eq 1 ]; then
+              echo "Tox failed with exit code 1 (attempt $attempt). Attempting to commit changes..."
+              git add .
+              git commit -m "chore: commit changes for release"
+              echo "Changes committed. Retrying..."
+            else
+              echo "Tox failed with exit code $exit_code (attempt $attempt)."
+            fi
+
             attempt=$(( attempt + 1 ))
-            echo "Tox failed (attempt $attempt). Retrying in 10 seconds..."
+            echo "Retrying in 10 seconds..."
             sleep 10
           done
           if [ $attempt -ge $max_attempts ]; then
